export const CLEAR_ALERT = 'CLEAR_ALERT';
export const FETCH_BEGIN = 'FETCH_BEGIN';

export const GET_ALLTOURS_SUCCESS = 'GET_ALLTOURS_SUCCESS';

export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS';

export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';

export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const GET_USER_BOOKING_SUCCESS = 'GET_USER_BOOKING_SUCCESS';
export const GET_USER_BOOKING_ERROR = 'GET_USER_BOOKING_ERROR';

export const GET_USER_REVIEWS_SUCCESS = 'GET_USER_REVIEWS_SUCCESS';
export const GET_USER_REVIEWS_ERROR = 'GET_USER_REVIEWS_ERROR';
